### ISSUE TITLE
[RFC] v1.0.0

### ISSUE THREAD

**Issue by nor-ko-hi-jp** [nor-ko-hi-jp/firex-store#35]
Tell me what you think, please!

I will update this!!

### Add
- [x] #38 `on` helper, like `from` helper
  - [v1.0.0]  on('').unsubscribe(state)
  - [v1.0.0-alpha] FirestoreUnsubscriber.unbind('').unsubscribe(state)

- [x] #39 doc: `v1/difference-from-v0.md`

### Change
- [x] #36 parameter of `unbind`, FirestoreUnsubscriber method 
  - [v1.0.0] statePropName: string  // state property name
  - [v1.0.0-alpha] type: 'document' | 'collection'

- [x] #38 creator method name of FirestoreUnsubscriber
  - [v1.0.0] on(statePropName: string)
  - [v1.0.0-alpha] unbind(statePropName: string)

- [x] #36 parameter of firestoreUnsubscribeAction method 
  - [v1.0.0] FirestoreUnsuscriber instance and { type:  'document' | 'collection', actionName: string | undefined }
  - [v1.0.0-alpha] FirestoreUnsuscriber instance and { actionName: string | undefined }

- [x] #37 default return value of `find` and `findAll`, FirestoreFinder method in case of error occured
  - [v1.0.0] firestore data | error
  - [v1.0.0-alpha] firestore data | error | void

**Comment by nor-ko-hi-jp** [comment]
- Add ↑ case in `Change`
  - `method name of FirestoreUnsubscriber`

- Change ↑ case in `Add`
  - `on` helper, like from helper  <- before: `unbind` helper

**Comment by nor-ko-hi-jp** [comment]
- Add ↑ case in `Add` 
  - `doc: difference from v0`
